# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeNumber', models.IntegerField(default=0)),
                ('episodeName', models.CharField(max_length=100)),
                ('episodeDescription', models.CharField(max_length=200)),
                ('viewedEpisode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSeries', models.CharField(max_length=100)),
                ('numberSeries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTvShow', models.CharField(max_length=50)),
                ('apparitionDate', models.DateField(verbose_name='date aired')),
                ('endDate', models.DateField(verbose_name='end date')),
                ('episodeDuration', models.IntegerField(default=0)),
                ('shortDescription', models.CharField(max_length=200)),
                ('genreTvShow', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='tvShow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TvShow'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Series'),
        ),
    ]
