# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20180719_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='watchers',
        ),
        migrations.AddField(
            model_name='episode',
            name='users',
            field=models.ManyToManyField(related_name='users', through='polls.EpisodeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
